### ISSUE TITLE
Same user got this 86 times in 1 day: Fatal Exception: android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by cesarferreira** [sematext/sematext-logsene-android#26]
```
Fatal Exception: android.database.sqlite.SQLiteException: no such column: ١ (code 1 SQLITE_ERROR[1]): , while compiling: DELETE FROM objects WHERE `id` IN (SELECT `id` FROM objects ORDER BY `id` ASC limit ١);
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
       at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
       at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2321)
       at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
       at com.sematext.logseneandroid.SqliteObjectQueue.remove(SqliteObjectQueue.java:138)
       at com.sematext.logseneandroid.SqliteObjectQueue.add(SqliteObjectQueue.java:104)
       at com.sematext.logseneandroid.Logsene.addToQueue(Logsene.java:322)
       at com.sematext.logseneandroid.Logsene.event(Logsene.java:234)
```

phone: Galaxy S10
android version: 10

```xml
        <meta-data
            android:name="LogseneReceiverUrl"
            android:value="https://logsene-receiver.eu.sematext.com" />
```

**Comment by gr0** [comment]
Hi, thanks for reporting the issue. Can you share a bit more details on when it happens, what version you are using, etc? Also what is the environment, Android version, etc. 

You can also provide PR with the fix if you wish ;)

**Comment by cesarferreira** [comment]
`ASC limit %d` the `%d` is `١` which is `1` in Arabic, but why would it use that instead of `1`? and make this crash

**Comment by gr0** [comment]
Seems like it may be related to `Locale` and `String.format` method in the `SqliteObjectQueue`. I'll try to reproduce that and provide a new version of the library with the fix. Hopefully I will make it today.

**Comment by gr0** [comment]
I just created the `2.4.1` release. Please test it, it should fix the issue.
